@startuml
skinparam dpi 600

allow_mixing
hide empty members

'Image
class ChatMessage {
  +String message
}
class ChatRequest
class ChatResponse
class Choice
ChatRequest --> "*" ChatMessage
ChatResponse --> "*" Choice
Choice --> ChatMessage
@enduml
