##################################################################
# VS Code with REST Client extension is needed to use this file.
# Download at: https://aka.ms/vscode/rest-client
##################################################################

@api_host = http://localhost:3000

# Chat with the bot
POST {{api_host}}/chat
Content-Type: application/json

{
  "messages": [{
    "content": "How to search and book rentals?",
    "role": "user"
  }]
}

###

# Chat with the bot using streaming
POST {{api_host}}/chat
Content-Type: application/json

{
  "messages": [{
    "content": "How to search and book rentals?",
    "role": "user"
  }],
  "stream": true
}
