name: Build workshop docs
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20
      - name: Install tools
        run: npm i -g @moaw/cli
      - name: Build and update docs
        run: |
          git config --global user.name "sinedied"
          git config --global user.email "noda@free.fr"
          ./scripts/repo/build-docs.sh
